FROM python:3.11-slim

WORKDIR /app

# Copy the Fares service with CSV data
COPY fares/main.py .
COPY fares/fares.csv .
COPY fares/fares2.csv .

# Install FastAPI, Uvicorn, and Kafka support
RUN pip install --no-cache-dir fastapi uvicorn[standard] kafka-python requests
RUN apt-get update && apt-get install -y curl
# Expose the port
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD python -c "import httpx; httpx.get('http://localhost:8000/', timeout=5)" || exit 1

# Run the service
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["python", "main.py"]


