FROM python:3.11-slim

WORKDIR /app

# Copy the Flight Status consumer service
COPY flightStatus/main.py .

# Install required dependencies
RUN pip install --no-cache-dir kafka-python fastapi pydantic httpx

# Run the flight status service
CMD ["python", "main.py"]
