apiVersion: v1
kind: Service
metadata:
  name: fares-service
  namespace: default
  labels:
    app: fares
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 30001
    name: http
  selector:
    app: fares
