apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- fares-deployment.yaml
- fares-service.yaml
- faresapi-deployment.yaml
- faresapi-service.yaml
- apigateway-deployment.yaml
- apigateway-service.yaml
- faresui-deployment.yaml
- faresui-service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: arqui-soft3
